name: Pipeline
on: [push]
jobs:
  run-prettier:
    name: Running Prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install NodeJS Dependencies
        run: npm ci
      - name: Run Formatter
        run: npx prettier -c .
  run-linter:
    name: Running Linter
    needs: [run-prettier]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install NodeJS Dependencies
        run: npm ci
      - name: Run Linter
        run: npx eslint . --ext .ts
  run-unit-test:
    name: Running Unit Tests
    needs: [run-prettier, run-linter]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install NodeJS Dependencies
        run: npm ci && npm run build && npx tsc && npm run test
      # - name: Run Unit Tests
      #   run: npx jest --coverage
  run-iac-scan:
    name: Running IAC Scan
    needs: [run-prettier, run-linter, run-unit-test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install NodeJS Dependencies
        run: npm ci && npm install -g aws-cdk && npx tsc
      - name: CDK Synthesize
        run: cdk synth
      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: src/cdk.out/
          framework: cloudformation
          hard_fail_on: HIGH
          skip_check: CKV_AWS_18, CKV_AWS_116, CKV_AWS_117
      # - name: Set Up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      # - run: pip install checkov && checkov -d cdk.out/ --framework cloudformation -s --hard-fail-on critical,high
